In [ ]:
import pandas as pd

In [ ]:
df_json=pd.read_csv('/content/json_clear.csv')
df_csv=pd.read_csv('/content/csv_clear.csv', dtype = {'TicketNumber': str})
df_yaml=pd.read_csv('/content/yaml_clear.csv')
df_tab=pd.read_csv('/content/tab_cleared.csv', dtype = {'ProgrammNumber': str, 'TicketNumber': str})
df_xml=pd.read_csv('/content/xml_cleared.csv')
df_xlsx=pd.read_csv('/content/xlsx_clear.csv')

#JSON + YAML

In [ ]:
df_yaml=df_yaml.drop('Unnamed: 0', axis = 1)
df_yaml['ProgrammNumber']=df_yaml['ProgrammNumber'].astype('str')
df_yaml['DepartureDate']=df_yaml['DepartureDate'].astype('datetime64[ns]')

In [ ]:
df_json=df_json.drop('Unnamed: 0', axis = 1)
df_json['ProgrammNumber']=df_json['ProgrammNumber'].astype('int')
df_json['ProgrammNumber']=df_json['ProgrammNumber'].astype('str')
df_json['DepartureDate']=df_json['DepartureDate'].astype('datetime64[ns]')

In [56]:
df_json

,FirstName,LastName,Sex,DepartureDate,FlightNumber,Share Code,CityArrival,AirportArrival,CityDeparture,AirportDeparture,NickName,Status,Programm,ProgrammNumber
0,NaN,NaN,Male,2017-03-04,DL3377,False,Pittsburgh PA,PIT,Boston MA,BOS,FrequentFlyer0,Basic,KE,889215424
1,NaN,NaN,Male,2017-03-04,DL3377,False,Pittsburgh PA,PIT,Boston MA,BOS,FrequentFlyer0,Elite+,DT,484697244
2,NaN,NaN,Male,2017-07-21,DL3630,False,Detroit MI,DTW,Green Bay WI,GRB,FrequentFlyer0,Basic,KE,889215424
3,NaN,NaN,Male,2017-07-21,DL3630,False,Detroit MI,DTW,Green Bay WI,GRB,FrequentFlyer0,Elite+,DT,484697244
4,NaN,NaN,Male,2017-03-22,DL5361,False,New York NY,LGA,Pittsburgh PA,PIT,FrequentFlyer0,Basic,KE,889215424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1747126,NaN,NaN,Male,2017-06-26,SU1185,False,Moscow,SVO,Volgograd,VOG,FrequentFlyer99996,Elite,DT,702680548
1747127,NaN,NaN,Male,2017-05-07,SU2033,False,Moscow,SVO,Budapest,BUD,FrequentFlyer99996,Elite+,FB,183116620
1747128,NaN,NaN,Male,2017-05-07,SU2033,False,Moscow,SVO,Budapest,BUD,FrequentFlyer99996,Elite+,KE,275536799
1747129,NaN,NaN,Male,2017-05-07,SU2033,False,Moscow,SVO,Budapest,BUD,FrequentFlyer99996,Elite,SU,449778932
1747130,NaN,NaN,Male,2017-05-07,SU2033,False,Moscow,SVO,Budapest,BUD,FrequentFlyer99996,Elite,DT,702680548

In [ ]:
df_yaml

,DepartureDate,FlightNumber,ProgrammNumber,Programm,Class,Fare,AirportDeparture,AirportArrival
0,2017-01-01,AF1145,520518073,FB,Y,YRSTFN,SVO,CDG
1,2017-01-01,AF1844,18427809,FB,Y,YGRPZR,SVO,CDG
2,2017-01-01,AF4855,993927664,KE,Y,YRSTJQ,SVO,CDG
3,2017-01-01,AF4901,789402704,SU,Y,YGRPAT,SVO,CDG
4,2017-01-01,AZ545,352734424,KE,Y,YFLXKO,SVO,FCO
...,...,...,...,...,...,...,...,...
1687048,2018-01-01,VN8067,182808803,DT,Y,YGRPMT,SGN,VCS
1687049,2018-01-01,VN8067,88616357,FB,Y,YFLXDJ,SGN,VCS
1687050,2018-01-01,VN813,574004748,DT,Y,YGRPAU,SGN,REP
1687051,2018-01-01,VN8204,425304412,KE,Y,YSTNDC,HAN,DIN
1687052,2018-01-01,VN920,778810779,KE,Y,YRSTGK,PNH,VTE

In [ ]:
unit_yaml_json = pd.merge(df_yaml, df_json, on=['ProgrammNumber','Programm', 'FlightNumber', 'AirportArrival', 'AirportDeparture','DepartureDate'], how='outer', suffixes=('_yaml', '_json'))

In [ ]:
unit_yaml_json

,DepartureDate,FlightNumber,ProgrammNumber,Programm,Class,Fare,AirportDeparture,AirportArrival,FirstName,LastName,Sex,Share Code,CityArrival,CityDeparture,NickName,Status
0,2017-05-03,CI9325,100004763,SU,Y,YRSTEX,YEG,YVR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-04-08,DL9409,100004763,SU,Y,YGRPIL,AMS,YEG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-01-08,SU1137,100004763,SU,Y,YRSTXJ,AER,SVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-25,UX1447,100004763,SU,A,AGRPLN,MAD,DUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-03-05,AZ7254,100007093,KE,Y,YRSTTH,MXP,BEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2407626,2017-10-29,MU762,999993640,DT,NaN,NaN,KOJ,PVG,AMINA,ANAN'EVA,Female,False,Shanghai,Kagoshima,FrequentFlyer17858,Elite
2407627,2017-09-16,MU9526,999993640,DT,NaN,NaN,WNZ,PVG,AMINA,ANAN'EVA,Female,True,Shanghai,Wenzhou,FrequentFlyer17858,Elite
2407628,2017-08-08,MU9907,999993640,DT,Y,YFLXHZ,TYN,WNZ,AMINA,ANAN'EVA,Female,False,Wenzhou,Taiyuan,FrequentFlyer17858,Elite
2407629,2017-01-01,SU1451,999993640,DT,NaN,NaN,KEJ,SVO,AMINA,ANAN'EVA,Female,False,Moscow,Kemerovo,FrequentFlyer17858,Elite
2407630,2017-01-30,SU3700,999993640,DT,NaN,NaN,SVO,WAW,AMINA,ANAN'EVA,Female,True,Warsaw,Moscow,FrequentFlyer17858,Elite

In [ ]:
unit_yaml_json.to_csv('merge_yaml_json.csv')

#TAB + YAML + JSON

In [ ]:
df_tab

,BirthDate,DepartureDate,DepartureTime,ArrivalDate,ArrivalTime,FlightNumber,AirportDeparture,AirportArrival,BookingCode,TicketNumber,TravelDoc,Meal,Class,AdditionalInfo,Programm,ProgrammNumber,AgentInfo,FirstName,SecondName,LastName
0,1999-05-15,2017-05-30,00:05,2017-05-30,08:05,SU1306,SVO,OVB,ZBQSPY,7360415302044672,9375 053270,NaN,J,S,SU,38116280,Go2See,ILDAR,DANIILOVICH,OZEROV
1,NaN,2017-12-27,02:15,2017-12-27,04:40,SU1323,MMK,SVO,MHPBBX,7398421117936516,2244 645520,KSML,Y,9,FB,284903754,NaN,SAMIR,TAMERLANOVICH,KOLOSOV
2,NaN,2017-09-19,06:40,2017-09-19,07:45,SU1481,KJA,SVO,REDLVB,5174973140468001,8115 961316,NaN,Y,F,NaN,NaN,KupiBilet,SNEZHANA,KONSTANTINOVNA,IGNATOVA
3,1999-05-02,2017-03-18,22:10,2017-03-19,01:05,SU1180,SVO,VOG,NSJNGQ,5274206497242737,98 6865148,NaN,J,#,FB,884556993,Travelgenio,PLATON,ALBERTOVICH,ZHAROV
4,1990-12-26,2017-03-18,22:10,2017-03-19,01:05,SU1180,SVO,VOG,VWNYGF,6247422701565929,4396 926588,NaN,Y,NaN,SU,183142068,OZON.travel,NIKOLAI,IGOREVICH,NIKOLSKII
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155752,NaN,2017-02-14,03:10,2017-02-14,04:00,SU1181,VOG,SVO,JYYXED,4714800502596692,3511 319326,STML,Y,F,NaN,NaN,OneTwoTrip,MIROSLAV,SVIATOSLAVOVICH,EMELIANOV
155753,NaN,2017-02-14,03:10,2017-02-14,04:00,SU1181,VOG,SVO,XDKDZF,6730365623280343,2199 078129,NaN,Y,T,DT,261604825,OZON.travel,ARTEMII,GERMANOVICH,TARASOV
155754,1970-10-28,2017-02-14,03:10,2017-02-14,04:00,SU1181,VOG,SVO,SOWGLC,1569746161308219,7351 760618,NaN,Y,F,FB,902862806,Aeroflot,BORIS,SVIATOGOROVICH,GOROHOV
155755,1994-02-14,2017-05-18,06:30,2017-05-18,08:35,SU1158,SVO,ROV,SNRBXU,8653871661040452,3256 077151,NaN,Y,#,NaN,NaN,NaN,RAMIL,SVIATOSLAVOVICH,DOROFEEV
155756,NaN,2017-05-09,07:00,2017-05-09,08:35,SU1279,KZN,SVO,JMGRLT,5113294821402227,8328 780960,NaN,Y,NaN,DT,520710243,Aerobilet,VARVARA,DANILOVNA,SHAPOVALOVA

In [ ]:
type(df_tab.iloc[1]['ArrivalDate'])

str

In [ ]:
df_tab['BirthDate']=df_tab['BirthDate'].astype('datetime64[ns]')
df_tab['DepartureDate']=df_tab['DepartureDate'].astype('datetime64[ns]')
df_tab['ArrivalDate']=df_tab['ArrivalDate'].astype('datetime64[ns]')
df_tab['DepartureTime']=pd.to_datetime(df_tab['DepartureTime'],format= '%H:%M' ).dt.time
df_tab['ArrivalTime']=pd.to_datetime(df_tab['ArrivalTime'],format= '%H:%M' ).dt.time

In [ ]:
df_tab

,BirthDate,DepartureDate,DepartureTime,ArrivalDate,ArrivalTime,FlightNumber,AirportDeparture,AirportArrival,BookingCode,TicketNumber,TravelDoc,Meal,Class,AdditionalInfo,Programm,ProgrammNumber,AgentInfo,FirstName,SecondName,LastName
0,1999-05-15,2017-05-30,00:05:00,2017-05-30,08:05:00,SU1306,SVO,OVB,ZBQSPY,7360415302044672,9375 053270,NaN,J,S,SU,38116280,Go2See,ILDAR,DANIILOVICH,OZEROV
1,NaT,2017-12-27,02:15:00,2017-12-27,04:40:00,SU1323,MMK,SVO,MHPBBX,7398421117936516,2244 645520,KSML,Y,9,FB,284903754,NaN,SAMIR,TAMERLANOVICH,KOLOSOV
2,NaT,2017-09-19,06:40:00,2017-09-19,07:45:00,SU1481,KJA,SVO,REDLVB,5174973140468001,8115 961316,NaN,Y,F,NaN,NaN,KupiBilet,SNEZHANA,KONSTANTINOVNA,IGNATOVA
3,1999-05-02,2017-03-18,22:10:00,2017-03-19,01:05:00,SU1180,SVO,VOG,NSJNGQ,5274206497242737,98 6865148,NaN,J,#,FB,884556993,Travelgenio,PLATON,ALBERTOVICH,ZHAROV
4,1990-12-26,2017-03-18,22:10:00,2017-03-19,01:05:00,SU1180,SVO,VOG,VWNYGF,6247422701565929,4396 926588,NaN,Y,NaN,SU,183142068,OZON.travel,NIKOLAI,IGOREVICH,NIKOLSKII
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155752,NaT,2017-02-14,03:10:00,2017-02-14,04:00:00,SU1181,VOG,SVO,JYYXED,4714800502596692,3511 319326,STML,Y,F,NaN,NaN,OneTwoTrip,MIROSLAV,SVIATOSLAVOVICH,EMELIANOV
155753,NaT,2017-02-14,03:10:00,2017-02-14,04:00:00,SU1181,VOG,SVO,XDKDZF,6730365623280343,2199 078129,NaN,Y,T,DT,261604825,OZON.travel,ARTEMII,GERMANOVICH,TARASOV
155754,1970-10-28,2017-02-14,03:10:00,2017-02-14,04:00:00,SU1181,VOG,SVO,SOWGLC,1569746161308219,7351 760618,NaN,Y,F,FB,902862806,Aeroflot,BORIS,SVIATOGOROVICH,GOROHOV
155755,1994-02-14,2017-05-18,06:30:00,2017-05-18,08:35:00,SU1158,SVO,ROV,SNRBXU,8653871661040452,3256 077151,NaN,Y,#,NaN,NaN,NaN,RAMIL,SVIATOSLAVOVICH,DOROFEEV
155756,NaT,2017-05-09,07:00:00,2017-05-09,08:35:00,SU1279,KZN,SVO,JMGRLT,5113294821402227,8328 780960,NaN,Y,NaN,DT,520710243,Aerobilet,VARVARA,DANILOVNA,SHAPOVALOVA

In [ ]:
unit_yaml_json

,DepartureDate,FlightNumber,ProgrammNumber,Programm,Class,Fare,AirportDeparture,AirportArrival,FirstName,LastName,Sex,Share Code,CityArrival,CityDeparture,NickName,Status,LatitudeArrival,LongitudeArrival,LatitudeDeparture,LongitudeDeparture
0,2017-05-03,CI9325,100004763,SU,Y,YRSTEX,YEG,YVR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.195,-123.182,53.310,-113.580
1,2017-04-08,DL9409,100004763,SU,Y,YGRPIL,AMS,YEG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.310,-113.580,52.309,4.764
2,2017-01-08,SU1137,100004763,SU,Y,YRSTXJ,AER,SVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.972,37.415,43.446,39.947
3,2017-08-25,UX1447,100004763,SU,A,AGRPLN,MAD,DUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.289,6.767,40.472,-3.561
4,2017-03-05,AZ7254,100007093,KE,Y,YRSTTH,MXP,BEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.813,35.489,45.631,8.728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2407626,2017-10-29,MU762,999993640,DT,NaN,NaN,KOJ,PVG,AMINA,ANAN'EVA,Female,False,Shanghai,Kagoshima,FrequentFlyer17858,Elite,NaN,NaN,31.803,130.719
2407627,2017-09-16,MU9526,999993640,DT,NaN,NaN,WNZ,PVG,AMINA,ANAN'EVA,Female,True,Shanghai,Wenzhou,FrequentFlyer17858,Elite,NaN,NaN,0.000,0.000
2407628,2017-08-08,MU9907,999993640,DT,Y,YFLXHZ,TYN,WNZ,AMINA,ANAN'EVA,Female,False,Wenzhou,Taiyuan,FrequentFlyer17858,Elite,0.000,0.000,37.747,112.629
2407629,2017-01-01,SU1451,999993640,DT,NaN,NaN,KEJ,SVO,AMINA,ANAN'EVA,Female,False,Moscow,Kemerovo,FrequentFlyer17858,Elite,55.972,37.415,55.270,86.107
2407630,2017-01-30,SU3700,999993640,DT,NaN,NaN,SVO,WAW,AMINA,ANAN'EVA,Female,True,Warsaw,Moscow,FrequentFlyer17858,Elite,52.166,20.967,55.972,37.415

In [ ]:
coords_dep = pd.read_csv('GlobalAirportDatabase.txt', sep=':', header=None)[[1,14,15]].rename(columns={1:'AirportDeparture', 14: 'LatitudeDeparture', 15:'LongitudeDeparture'}).dropna().drop_duplicates('AirportDeparture')
coords_arr = pd.read_csv('GlobalAirportDatabase.txt', sep=':', header=None)[[1,14,15]].rename(columns={1:'AirportArrival', 14: 'LatitudeArrival', 15:'LongitudeArrival'}).dropna().drop_duplicates('AirportArrival')

In [ ]:
unit_yaml_json = pd.merge(unit_yaml_json, coords_arr, on = ['AirportArrival'], how='left')
unit_yaml_json = pd.merge(unit_yaml_json, coords_dep, on = ['AirportDeparture'], how='left')

In [ ]:
unit_yaml_json.to_csv('merge_yaml_json.csv')

In [ ]:
unit_tab_json_yaml = pd.merge(unit_yaml_json, df_tab, on = ['DepartureDate', 'FlightNumber', 'ProgrammNumber', 'Programm', 'AirportDeparture','Class', 'AirportArrival', 'FirstName', 'LastName' ],how='outer', suffixes=('_yaml_json', '_tab') )

In [ ]:
unit_tab_json_yaml

,DepartureDate,FlightNumber,ProgrammNumber,Programm,Class,Fare,AirportDeparture,AirportArrival,FirstName,LastName,...,DepartureTime,ArrivalDate,ArrivalTime,BookingCode,TicketNumber,TravelDoc,Meal,AdditionalInfo,AgentInfo,SecondName
0,2017-01-01,AF1145,520518073,FB,Y,YRSTFN,SVO,CDG,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-01-01,AF1844,18427809,FB,Y,YGRPZR,SVO,CDG,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-01-01,AF1844,206575495,KE,NaN,NaN,SVO,CDG,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-01-01,AF1844,363105640,SU,NaN,NaN,SVO,CDG,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-01-01,AF1844,425998795,DT,NaN,NaN,SVO,CDG,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2558436,2018-01-01,VN8067,515946050,SU,NaN,NaN,SGN,VCS,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2558437,2018-01-01,VN8067,88616357,FB,Y,YFLXDJ,SGN,VCS,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2558438,2018-01-01,VN813,574004748,DT,Y,YGRPAU,SGN,REP,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2558439,2018-01-01,VN8204,425304412,KE,Y,YSTNDC,HAN,DIN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2558440,2018-01-01,VN920,778810779,KE,Y,YRSTGK,PNH,VTE,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
unit_tab_json_yaml.to_csv('merge_tab_json_yaml.csv')

#CSV + XLSX

In [ ]:
df_csv=df_csv.drop('Unnamed: 0', axis =1).rename(columns={'CityDeparture':'CityArrival', 'LatitudeDeparture':'LatitudeArrival', 'LongitudeDeparture':'LongitudeArrival'})

In [ ]:
df_csv['BirthDate']=df_csv['BirthDate'].astype('datetime64[ns]')
df_csv['Document']=df_csv['Document'].astype('str')
df_csv['DepartureDate']=df_csv['DepartureDate'].astype('datetime64[ns]')
df_csv['DepartureTime']=pd.to_datetime(df_csv['DepartureTime'],format= '%H:%M' ).dt.time

In [ ]:
df_csv

,FirstName,SecondName,LastName,Sex,BirthDate,Document,PNR,TicketNumber,Baggage,DepartureDate,DepartureTime,FlightNumber,CodeShare,CityArrival,LatitudeArrival,LongitudeArrival
0,SAVELII,VIKTOROVICH,RUSANOV,Male,1983-03-10,2879 096860,FRNINO,6625956945991971,Transit,2017-03-22,06:05:00,SU1369,Own,Moscow,55.972,37.415
1,LEV,MARKOVICH,ISAEV,Male,1975-12-13,1788 173211,NaN,1643715499224676,Registered,2017-03-18,22:10:00,SU1180,Own,Volgograd,48.782,44.345
2,NIKOLAI,IGOREVICH,NIKOLSKII,Male,1990-12-26,4396 926588,VWNYGF,6247422701565929,Transit,2017-03-18,22:10:00,SU1180,Own,Volgograd,48.782,44.345
3,ANATOLII,PETROVICH,SHILOV,Male,1997-05-24,2595 919752,WQFFUE,NaN,Registered,2017-03-18,22:10:00,SU1180,Own,Volgograd,48.782,44.345
4,MIROSLAVA,VIACHESLAVOVNA,SEMENOVA,Female,1976-01-31,6775 516990,NaN,NaN,Registered,2017-03-12,11:45:00,SU6284,Own,Moscow,55.972,37.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155138,RAMIL,SVIATOSLAVOVICH,DOROFEEV,Male,1994-02-14,3256 077151,SNRBXU,8653871661040452,Delayed,2017-05-18,06:30:00,SU1158,Own,Rostov,47.258,39.818
155139,RUSLAN,KONSTANTINOVICH,CHISTIAKOV,Male,1975-02-14,3497 458395,NaN,0223584175158947,NaN,2017-05-18,06:30:00,SU1158,Own,Rostov,47.258,39.818
155140,SOFIA,VALEREVNA,KALMYKOVA,Female,1972-12-17,6618 352713,NaN,NaN,Registered,2017-10-02,07:30:00,SU5614,Own,Petropavlovsk,53.166,158.453
155141,VIACHESLAV,FEDOROVICH,KONONOV,Male,2000-05-20,4567 242088,NaN,0975693658645383,Registered,2017-09-16,07:00:00,SU1640,Own,Omsk,54.967,73.310
155142,ESENIIA,DANILOVNA,BLINOVA,Female,1984-03-07,2861 762272,NaN,NaN,NaN,2017-05-09,07:00:00,SU1279,Own,Moscow,55.972,37.415

In [ ]:
df_xlsx=df_xlsx.drop(columns=['Unnamed: 0', 'WeekDay', 'Months', 'Hours'], axis =1)

In [ ]:
df_xlsx.keys()

Index(['DepartureDate', 'DepartureTime', 'FlightNumber', 'Class',
       'CityDeparture', 'AirportDeparture', 'CityArrival', 'AirportArrival',
       'PNR', 'TicketNumber', 'Sequence', 'Sex', 'FirstName', 'SecondName',
       'LastName', 'LatitudeDeparture', 'LongitudeDeparture',
       'LatitudeArrival', 'LongitudeArrival'],
      dtype='object')

In [ ]:
df_csv.keys()

Index(['FirstName', 'SecondName', 'LastName', 'Sex', 'BirthDate', 'Document',
       'PNR', 'TicketNumber', 'Baggage', 'DepartureDate', 'DepartureTime',
       'FlightNumber', 'CodeShare', 'CityArrival', 'LatitudeArrival',
       'LongitudeArrival'],
      dtype='object')

In [ ]:
df_xlsx['TicketNumber']=df_xlsx['TicketNumber'].astype('str')
df_xlsx['DepartureDate']=df_xlsx['DepartureDate'].astype('datetime64[ns]')
df_xlsx['DepartureTime']=pd.to_datetime(df_xlsx['DepartureTime'],format= '%H:%M' ).dt.time

In [ ]:
unit_csv_xlsx = pd.merge(df_csv, df_xlsx, on = ['DepartureDate', 'DepartureTime','Sex', 'LatitudeArrival', 'LongitudeArrival', 'FlightNumber', 'CityArrival', 'PNR','TicketNumber', 'FirstName', 'SecondName', 'LastName' ],how='outer', suffixes=('_csv', '_xlsx') )

In [ ]:
unit_csv_xlsx

,FirstName,SecondName,LastName,Sex,BirthDate,Document,PNR,TicketNumber,Baggage,DepartureDate,...,CityArrival,LatitudeArrival,LongitudeArrival,Class,CityDeparture,AirportDeparture,AirportArrival,Sequence,LatitudeDeparture,LongitudeDeparture
0,ANNA,ALEKSANDROVNA,EVSEEVA,Female,1982-06-27,9541 369051,AELQCE,7633256772878804,NaN,2017-01-01,...,Omsk,54.967,73.310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ANNA,NaN,EVSEEVA,Female,NaT,NaN,AELQCE,7633256772878804,NaN,2017-01-01,...,Omsk,54.967,73.310,Y,Moscow,SVO,OMS,1.0,55.972,37.415
2,NATALIA,NaN,OLEINIKOVA,Female,NaT,NaN,WMUYKE,7960596998657567,NaN,2017-01-01,...,Novosibirsk,0.000,0.000,Y,Moscow,SVO,OVB,17.0,55.972,37.415
3,KIRA,NaN,KOLESOVA,Female,NaT,NaN,BLQDOG,7998476726624714,NaN,2017-01-01,...,Vladivostok,43.399,132.151,Y,Khabarovsk,KHV,VVO,97.0,48.528,135.188
4,STEFANIIA,A.,GLUSHKOVA,Female,1970-03-04,0160 634139,IIGYXG,NaN,NaN,2017-01-01,...,Vladivostok,43.399,132.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770909,SAMIR,NaN,NIKULIN,Male,NaT,NaN,YHEZTI,3836481123848906,NaN,2018-01-01,...,Rio de janeiro,-22.809,-43.244,Y,Paris,CDG,GIG,43.0,49.013,2.550
770910,IAROMIR,NaN,BASHIROV,Male,NaT,NaN,AHADSU,8081503155741763,NaN,2018-01-01,...,Moscow,55.972,37.415,Y,Rome,FCO,SVO,32.0,41.813,12.253
770911,AMINA,NaN,SHISHKINA,Female,NaT,NaN,DOOITM,1329040900912585,NaN,2018-01-01,...,Casablanca,33.368,-7.588,P,Jeddah,JED,CMN,60.0,21.679,39.156
770912,IAROMIR,Y,EVSEEV,Male,NaT,NaN,BIACQI,3478305682803417,NaN,2018-01-01,...,Kaliningrad,54.890,20.592,Y,Saint petersburg,LED,KGD,31.0,59.800,30.265
770913,IAN,L,PAVLOVSKII,Male,NaT,NaN,PMAWOJ,1600306237892227,NaN,2018-01-01,...,Moscow,55.972,37.415,Y,Saint petersburg,LED,SVO,11.0,59.800,30.265

In [ ]:
unit_csv_xlsx.to_csv('merge_csv_xlsx.csv')

#JSON+YAML+TAB+XML

In [ ]:
df_xml

,FirstName,LastName,FlightNumber,DepartureDate,AirportDeparture,AirportArrival,Programm,ProgrammNumber
0,IAROMIR,ZVEREV,KE827,2017-08-06,REA,SZX,FB,171388778
1,IAROMIR,ZVEREV,MU9706,2017-10-26,PEK,BSD,FB,171388778
2,VITALINA,KOROVINA,DL5058,2017-09-11,CHA,ATL,KE,696768759
3,VITALINA,KOROVINA,KE1,2017-04-01,REA,HNL,KE,696768759
4,VITALINA,KOROVINA,DL837,2017-09-13,ATL,HNL,KE,696768759
...,...,...,...,...,...,...,...,...
436085,EMIL,KAZAKOV,SU6402,2017-03-01,SVX,LED,DT,269347755
436086,EMIL,KAZAKOV,AR1142,2017-12-14,EZE,FCO,SU,856232932
436087,EMIL,KAZAKOV,AR1143,2017-09-16,FCO,EZE,SU,856232932
436088,ULIANA,KONONOVA,GA502,2017-05-12,CGK,PNK,DT,302785701
436089,ULIANA,KONONOVA,GA88,2017-08-02,CGK,AMS,DT,302785701

In [ ]:
df_xml = pd.merge(df_xml, coords_arr, on=['AirportArrival'], how='left')
df_xml = pd.merge(df_xml, coords_dep, on=['AirportDeparture'], how='left')

In [ ]:
df_xml.keys()

Index(['FirstName', 'LastName', 'FlightNumber', 'DepartureDate',
       'AirportDeparture', 'AirportArrival', 'Programm', 'ProgrammNumber',
       'LatitudeArrival', 'LongitudeArrival', 'LatitudeDeparture',
       'LongitudeDeparture'],
      dtype='object')

In [ ]:
df_xml['DepartureDate']=df_xml['DepartureDate'].astype('datetime64[ns]')
df_xml['ProgrammNumber']=df_xml['ProgrammNumber'].astype('str')

In [ ]:
unit_lp=pd.merge(unit_tab_json_yaml, df_xml, on=['FirstName', 'LastName', 'FlightNumber', 'DepartureDate', 'AirportDeparture', 'AirportArrival','Programm','ProgrammNumber', 'LatitudeArrival', 'LongitudeArrival', 'LatitudeDeparture', 'LongitudeDeparture' ], how = 'outer')

In [ ]:
unit_lp

,DepartureDate,FlightNumber,ProgrammNumber,Programm,Class,Fare,AirportDeparture,AirportArrival,FirstName,LastName,...,DepartureTime,ArrivalDate,ArrivalTime,BookingCode,TicketNumber,TravelDoc,Meal,AdditionalInfo,AgentInfo,SecondName
0,2017-03-17,AF1343,930869690,SU,NaN,NaN,GVA,CDG,ADEL,AGEEV,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-10-18,AM451,989004326,KE,NaN,NaN,MEX,HAV,ADEL,AGEEV,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-11-19,CZ6360,562855979,FB,NaN,NaN,CGO,SYX,ADEL,AGEEV,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-10-15,CZ6575,562855979,FB,NaN,NaN,CGO,SYX,ADEL,AGEEV,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-07-26,DL2107,562855979,FB,NaN,NaN,SFO,LAX,ADEL,AGEEV,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935417,2017-11-24,VN957,638476586,FB,Y,YFLXAA,HAN,RGN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935418,2017-12-03,VN957,967537639,SU,Y,YSTNEY,HAN,RGN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935419,2017-12-16,VN957,634313487,SU,A,AFLXGJ,HAN,RGN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935420,2017-12-31,VN957,708008527,FB,Y,YGRPUV,HAN,RGN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935421,2017-12-31,VN957,156623300,KE,Y,YRSTQQ,HAN,RGN,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
unit_lp.to_csv('JSON+YAML+TAB+XML.csv')

#ALL

In [ ]:
unit_csv_xlsx

,FirstName,SecondName,LastName,Sex,BirthDate,Document,BookingCode,TicketNumber,Baggage,DepartureDate,...,CityArrival,LatitudeArrival,LongitudeArrival,Class,CityDeparture,AirportDeparture,AirportArrival,Sequence,LatitudeDeparture,LongitudeDeparture
0,ANNA,ALEKSANDROVNA,EVSEEVA,Female,1982-06-27,9541 369051,AELQCE,7633256772878804,NaN,2017-01-01,...,Omsk,54.967,73.310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ANNA,NaN,EVSEEVA,Female,NaT,NaN,AELQCE,7633256772878804,NaN,2017-01-01,...,Omsk,54.967,73.310,Y,Moscow,SVO,OMS,1.0,55.972,37.415
2,NATALIA,NaN,OLEINIKOVA,Female,NaT,NaN,WMUYKE,7960596998657567,NaN,2017-01-01,...,Novosibirsk,0.000,0.000,Y,Moscow,SVO,OVB,17.0,55.972,37.415
3,KIRA,NaN,KOLESOVA,Female,NaT,NaN,BLQDOG,7998476726624714,NaN,2017-01-01,...,Vladivostok,43.399,132.151,Y,Khabarovsk,KHV,VVO,97.0,48.528,135.188
4,STEFANIIA,A.,GLUSHKOVA,Female,1970-03-04,0160 634139,IIGYXG,NaN,NaN,2017-01-01,...,Vladivostok,43.399,132.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770909,SAMIR,NaN,NIKULIN,Male,NaT,NaN,YHEZTI,3836481123848906,NaN,2018-01-01,...,Rio de janeiro,-22.809,-43.244,Y,Paris,CDG,GIG,43.0,49.013,2.550
770910,IAROMIR,NaN,BASHIROV,Male,NaT,NaN,AHADSU,8081503155741763,NaN,2018-01-01,...,Moscow,55.972,37.415,Y,Rome,FCO,SVO,32.0,41.813,12.253
770911,AMINA,NaN,SHISHKINA,Female,NaT,NaN,DOOITM,1329040900912585,NaN,2018-01-01,...,Casablanca,33.368,-7.588,P,Jeddah,JED,CMN,60.0,21.679,39.156
770912,IAROMIR,Y,EVSEEV,Male,NaT,NaN,BIACQI,3478305682803417,NaN,2018-01-01,...,Kaliningrad,54.890,20.592,Y,Saint petersburg,LED,KGD,31.0,59.800,30.265
770913,IAN,L,PAVLOVSKII,Male,NaT,NaN,PMAWOJ,1600306237892227,NaN,2018-01-01,...,Moscow,55.972,37.415,Y,Saint petersburg,LED,SVO,11.0,59.800,30.265

In [57]:
unit_lp.keys()

Index(['DepartureDate', 'FlightNumber', 'ProgrammNumber', 'Programm', 'Class',
       'Fare', 'AirportDeparture', 'AirportArrival', 'FirstName', 'LastName',
       'Sex', 'CodeShare', 'CityArrival', 'CityDeparture', 'NickName',
       'Status', 'LatitudeArrival', 'LongitudeArrival', 'LatitudeDeparture',
       'LongitudeDeparture', 'BirthDate', 'DepartureTime', 'ArrivalDate',
       'ArrivalTime', 'BookingCode', 'TicketNumber', 'TravelDoc', 'Meal',
       'AdditionalInfo', 'AgentInfo', 'SecondName'],
      dtype='object')

In [62]:
unit_csv_xlsx.keys()

Index(['FirstName', 'SecondName', 'LastName', 'Sex', 'BirthDate', 'Document',
       'BookingCode', 'TicketNumber', 'Baggage', 'DepartureDate',
       'DepartureTime', 'FlightNumber', 'CodeShare', 'CityArrival',
       'LatitudeArrival', 'LongitudeArrival', 'Class', 'CityDeparture',
       'AirportDeparture', 'AirportArrival', 'Sequence', 'LatitudeDeparture',
       'LongitudeDeparture'],
      dtype='object')

In [ ]:
unit_csv_xlsx=unit_csv_xlsx.rename(columns={'PNR':'BookingCode'})

In [58]:
unit_lp=unit_lp.rename(columns={'TravelDoc':'Document'})

In [ ]:
unit_lp=unit_lp.rename(columns={'Share Code':'CodeShare'})

In [64]:
all_df=pd.merge(unit_csv_xlsx,unit_lp,on=['FirstName', 'Document','SecondName','Class', 'LastName', 'Sex', 'BirthDate', 'BookingCode', 'TicketNumber', 'DepartureDate', 'DepartureTime','FlightNumber', 'CodeShare', 'CityArrival', 'LatitudeArrival','LongitudeArrival',  'CityDeparture', 'AirportDeparture','AirportArrival','LatitudeDeparture','LongitudeDeparture'], how='outer')

In [ ]:
all_df

,FirstName,SecondName,LastName,Sex,BirthDate,Document,BookingCode,TicketNumber,Baggage,DepartureDate,...,Class_y,Fare,NickName,Status,ArrivalDate,ArrivalTime,TravelDoc,Meal,AdditionalInfo,AgentInfo
0,ADEL,A,AFANASEV,Male,NaT,NaN,JABYNO,3282520431467470,NaN,2017-03-11,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,ADEL,A,ANANEV,Male,NaT,NaN,DPRIHF,5591256208348976,NaN,2017-06-13,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,ADEL,A,BESSONOV,Male,NaT,NaN,HGPAPW,8694678677584331,NaN,2017-12-12,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3,ADEL,A,BESSONOV,Male,NaT,NaN,PYWFLR,5107740369874796,NaN,2017-12-19,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
4,ADEL,A,BOCHAROV,Male,NaT,NaN,FDUBZZ,2079442205578954,NaN,2017-06-05,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3706331,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2018-01-01,...,Y,YSTNIT,FrequentFlyer38113,Elite+,NaT,NaN,NaN,NaN,NaN,NaN
3706332,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2018-01-01,...,Y,YFLXDJ,FrequentFlyer21623,Basic,NaT,NaN,NaN,NaN,NaN,NaN
3706333,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2018-01-01,...,NaN,NaN,FrequentFlyer21623,Elite,NaT,NaN,NaN,NaN,NaN,NaN
3706334,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2018-01-01,...,Y,YSTNDC,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3706335,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2018-01-01,...,Y,YRSTGK,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [65]:
all_df.to_csv('all_formats.csv')